const strataModule = await import(process.env.STRATA_MODULE || new URL("../../../strata-ebo-turnstile/src/index.js", import.meta.url));

export const {
  ActionGateway,
  HttpWitnessClient,
  JsonlReceiptLog,
  LocalTransparencyLog,
  canonicalize,
  capabilityDigest,
  createAdmissionManifest,
  createTinfoilEvidence,
  createToolExecutionReceiptObject,
  createVerifierProfile,
  digestValue,
  loadOrCreateEd25519Signer,
  sha256Hex,
  signEd25519,
  signWitnessRegistryEpoch,
  signReceipt,
  toolRequestDigest,
  verifyCapability,
  verifyCheckpoint,
  verifyEd25519,
  verifyWitnessAuthority,
  verifyWitnessRegistryEpoch,
  witnessRegistryEpochDigest,
  WITNESS_REGISTRY_EPOCH_VERSION,
  admissionManifestDigest,
  verifySession,
  writeCheckpoint
} = strataModule;
